apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: cloud-dev.xyz
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://cloud-dev.xyz/cloud-dev.xyz
  dnsZone: cloud-dev.xyz
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1a
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1a
      name: a
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.30.2
  masterPublicName: api.cloud-dev.xyz
  networkCIDR: 172.20.0.0/16
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.0.0/17
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 172.20.128.0/17
    name: us-east-1b
    type: Public
    zone: us-east-1b
  topology:
    dns:
      type: Public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cloud-dev.xyz
  name: control-plane-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240607
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 10
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cloud-dev.xyz
  name: nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240607
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  rootVolumeSize: 10
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cloud-dev.xyz
  name: nodes-us-east-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240607
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  rootVolumeSize: 10
  subnets:
  - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: SSHCredential
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: cloud-dev.xyz
  name: admin
spec:
  publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDiU1QWqe8tuqPMBSlRaJS7d+N4DQ7GzalYx/kE4j70difDC8kFibl1881cdlCqoT6owdJyv5UuEtINr7Ijy2AKu/U5bmii008kMSTIwk6Zx+Rbysvd+kY6ZOeSbe+q+6Z/eLcVIdxQ7lUvuczQZiaX12UsrziDnXOLTw/YIM/KZyCKuY0pCGrYbaI90cDpfGBz5uWFsMpTAGiCXwQwbRgpjCwgSbH47hSB3f+A5HK2oNXGuep/i9pDCD4nrBdJGf6al8aASyQVDtWJxAYl3y2SsRrUYqP462K3I4Sc71dBAuG3/lsBkfWWLFvyaf8vADT8Qy82Kn7CXRYGRvqOM0c2IIHvdwVDfJImgJiqRxN+zbO4200Nzz/A8wp+5LQPIlEqb12PndhwCWJO9gcXvIh2LTcNV60VIPaBeHKl1ied692bVssZi+XZXZbPBmatSkj3cAqSkXgiPnvOWQEY3qEwObptZZwqcCTZBmpJ5PGjOcidbSWg1kGCDpboecedIpE=
    root@ip-172-31-18-207
